# Copyright (c) 2022 OpenFaaS Ltd
name: 'nvidia-run'
description: 'Download and install Nvidia drivers and Kernel modules'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
runs:
    using: 'composite'
    steps:
      - name: Download .run file
        shell: bash
        id: download-nvidia
        run: |
           RET=$(lspci|grep "3D controller")
           if [ $? == 0 ]
           then
             curl -o ./NVIDIA-Linux-x86_64.run -s -S -L https://us.download.nvidia.com/tesla/550.54.15/NVIDIA-Linux-x86_64-550.54.15.run \
                && chmod +x ./NVIDIA-Linux-x86_64.run
           else
             curl -o ./NVIDIA-Linux-x86_64.run -s -S -L -O https://us.download.nvidia.com/XFree86/Linux-x86_64/525.60.11/NVIDIA-Linux-x86_64-525.60.11.run \
               && chmod +x ./NVIDIA-Linux-x86_64.run
           fi
           chmod +x ./NVIDIA-Linux-x86_64.run

      - name: Build and install Nvidia drivers
        shell: bash
        id: install-nvidia
        run: |
          sudo ./NVIDIA-Linux-x86_64.run \
                  --accept-license \
                  --ui=none \
                  --no-questions \
                  --no-x-check \
                  --no-check-for-alternate-installs \
                  --no-nouveau-check
